import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="bg-blue-700 text-white px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1">
              <span className="text-2xl font-bold">hfiles</span>
            </div>
          </div>
          <div className="text-lg tracking-wider">HFiles Dashboard</div>
          <div className="w-10 h-10 rounded-full overflow-hidden border-2 border-white">
            <img src='/avatar.png' alt="User" className="w-full h-full object-cover" />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
